version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    container_name: gastos-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Fuerza a Vite a detectar cambios de archivos
      - CHOKIDAR_USEPOLLING=true